server:
  port: 8181

logging:
  level:
    com.backend.programming.learning.system: DEBUG

core-service:
  code-question-update-response-from-core-service-topic-name: code-question-update-response-from-core-service
  code-question-update-request-to-core-service-topic-name: code-question-update-request-to-core-service
  question-created-request-topic-name: core-question-create-request
  question-deleted-request-topic-name: core-question-delete-request
  question-updated-request-topic-name: core-question-update-request

  question-response-topic-name: core-question-response

  user-request-topic-name: user-request
  user-response-topic-name: user-response

  calendar-event-update-request-topic-name: calendar-event-update-request
  calendar-event-update-response-topic-name: calendar-event-update-response

  outbox-scheduler-fixed-rate: 2000
  outbox-scheduler-initial-delay: 2000

#spring:
#  jpa:
#    open-in-view: false
#    show-sql: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/core-service?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
#    username: postgres
#    password: localdb
#    driver-class-name: org.postgresql.Driver
#  sql:
#    init:
#      platform: postgres
#      schema-locations: classpath:init-schema.sql
#      mode: always

spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  #        enable_lazy_load_no_trans: true
  #        event:
  #          merge:
  #            entity_copy_observer: allow
  datasource:
    url: jdbc:postgresql://localhost:5432/core-service?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    platform: postgres
    schema: classpath:init-schema.sql
    data: classpath:init-data.sql
    initialization-mode: always

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://192.168.1.21:8081
  num-of-partitions: 3
  replication-factor: 3

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.StringSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: none
  acks: all
  batch-size: 16384
  batch-size-boost-factor: 100
  linger-ms: 5
  request-timeout-ms: 60000
  retry-count: 5

kafka-consumer-config:
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
  core-service-user-consumer-group-id: core-service-user-topic-consumer

  core-service-question-consumer-group-id: core-service-question-topic-consumer

  core-service-calendar-event-consumer-group-id: core-service-calendar-event-topic-consumer

  core-service-user-request-group-id: core-service-user-create-topic

  customer-group-id: customer-topic-consumer
  code-question-update-consumer-group-id: code-question-update-topic-consumer
  auto-offset-reset: earliest
  specific-avro-reader-key: specific.avro.reader
  specific-avro-reader: true
  batch-listener: true
  auto-startup: true
  concurrency-level: 3
  session-timeout-ms: 10000
  heartbeat-interval-ms: 3000
  max-poll-interval-ms: 300000
  max-poll-records: 500
  max-partition-fetch-bytes-default: 1048576
  max-partition-fetch-bytes-boost-factor: 1
  poll-timeout-ms: 150
