gateway-service:
  timeout-ms: 10000
  failure-rate-threshold: 50
  slow-call-rate-threshold: 50
  slow-call-duration-threshold: 50
  permitted-num-of-calls-in-half-open-state: 10
  sliding-window-size: 10
  min-number-of-calls: 10
  wait-duration-in-open-state: 60000

server:
  port: 9098

spring:
  application:
    name: gateway-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            allowedHeaders:
              - "*"
#            allowCredentials: true
            maxAge: 3600
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: core-service
          uri: http://core-service:8181
          predicates:
            - Path=/core-service/**
          filters:
            - RewritePath=/core-service/(?<path>.*), /$\{path}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@authHeaderResolver}"
            - name: CircuitBreaker
              args:
                name: coreServiceCircuitBreaker
                fallbackUri: forward:/fallback/core-fallback
        - id: auth-service
          uri: http://auth-service:8182
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/(?<path>.*), /$\{path}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@authHeaderResolver}"
            - name: CircuitBreaker
              args:
                name: authServiceCircuitBreaker
                fallbackUri: forward:/fallback/auth-fallback
        - id: course-service
          uri: http://course-service:8184
          predicates:
            - Path=/course-service/**
          filters:
            - RewritePath=/course-service/(?<path>.*), /$\{path}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@authHeaderResolver}"
            - name: CircuitBreaker
              args:
                name: courseServiceCircuitBreaker
                fallbackUri: forward:/fallback/course-fallback
        - id: code-assessment-service
          uri: http://code-assessment-service:8183
          predicates:
            - Path=/code-assessment-service/**
          filters:
            - RewritePath=/code-assessment-service/(?<path>.*), /$\{path}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@authHeaderResolver}"
            - name: CircuitBreaker
              args:
                name: codeAssessmentServiceCircuitBreaker
                fallbackUri: forward:/fallback/code-assessment-fallback
  redis:
    host: 127.0.0.1
    port: 6379
    password: admin

security:
  paths-to-ignore: /actuator/**

management:
  endpoints:
    web:
      base-path: /actuator
      exposure.include: health, prometheus, gateway
      path-mapping.prometheus: metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      cache.time-to-live: 1ms

log:
  appName: gateway-service